service: psycopg2-lambda-layer

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  profile: jb
  stage: prod

layers:
  psycopg2-py38:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.9
    allowedAccounts:
      - '*'
    retain: true
